[build]
  publish = "."
  command = ""

[[headers]]
  for = "/invite.ics"
  [headers.values]
    Content-Type = "text/calendar; charset=utf-8"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/calendar"
  to = "/invite.ics"
  status = 200
